gitRepoUrl = "https://github.com/Superbithious/Postie"
gitSourceBranch = "main"

changelog = true

[home]
enabled = true
includeReadme = false

[docusaurus]
tagline = "A safe alternative to RemoteFunctions"

[[navbar.items]]
href = "https://wally.run/package/superbithious/postie"
label = "Wally"
position = "right"