[package]
name = "superbithious/postie"
description = "Postie is a safe alternative to RemoteFunction with a timeout."
version = "1.1.1"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["docs"]

[dependencies]